version: '3.8'

services:
  paytmuser-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.paytmUserApp
    image: anoopkarnik/turborepo-boilerplate-paytm-user-app:latest
    ports:
      - "3001:3001"
    networks:
      - turborepo-network

  paytmmerchant-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.paytmMerchantApp
    image: anoopkarnik/turborepo-boilerplate-paytm-merchant-app:latest
    ports:
      - "3002:3002"
    networks:
      - turborepo-network

  app-dashboard:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.appDashboard
    image: anoopkarnik/turborepo-boilerplate-app-dashboard:latest
    ports:
      - "3000:3000"
    networks:
      - turborepo-network

  backend-chat-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backendChatApp
    image: anoopkarnik/turborepo-boilerplate-backend-chat-app:latest
    ports:
      - "3004:3004"
    networks:
      - turborepo-network

  frontend-chat-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontendChatApp
    image: anoopkarnik/turborepo-boilerplate-frontend-chat-app:latest
    ports:
      - "3005:3005"
    networks:
      - turborepo-network
  
  fancy-web-pages-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.fancyWebPagesApp
    image: anoopkarnik/turborepo-boilerplate-fancy-web-pages-app:latest
    ports:
      - "3006:3006"
    networks:
      - turborepo-network
  
  blog-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontendBlogApp
    image: anoopkarnik/turborepo-boilerplate-blog-app:latest
    ports:
      - "3008:3008"
    networks:
      - turborepo-network

  backend-webrtc-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backendWebrtcApp
    image: anoopkarnik/turborepo-boilerplate-backend-webrtc-app:latest
    ports:
      - "3012:3012"
    networks:
      - turborepo-network

  frontend-webrtc-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontendWebrtcApp
    image: anoopkarnik/turborepo-boilerplate-frontend-webrtc-app:latest
    ports:
      - "3011:3011"
    networks:
      - turborepo-network

  # backend-chess-app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.backendChessApp
  #   image: anoopkarnik/turborepo-boilerplate-backend-chess-app:latest
  #   ports:
  #     - "3013:3013"
  #   networks:
  #     - turborepo-network

  # frontend-chess-app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.frontendChessApp
  #   image: anoopkarnik/turborepo-boilerplate-frontend-chess-app:latest
  #   ports:
  #     - "3014:3014"
  #   networks:
  #     - turborepo-network

networks:
  turborepo-network:
    driver: bridge