FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/frontend-webrtc-app ./apps/frontend-webrtc-app
COPY packages ./packages

EXPOSE 3011

RUN npm install

RUN npm run build

CMD ["npm", "run", "start-webrtc-app"]