FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/paytm-user-app ./apps/paytm-user-app
COPY packages ./packages

RUN npm install
RUN npm run db:generate

RUN npm run build

CMD ["npm", "run", "start-paytm-user-app"]