FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/frontend-chess-app ./apps/frontend-chess-app
COPY packages ./packages

EXPOSE 3014

RUN npm install

RUN npm run build

CMD ["npm", "run", "start-frontend-chess-app"]