FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/fancy-web-pages-app ./apps/fancy-web-pages-app
COPY packages ./packages

EXPOSE 3006

RUN npm install

RUN npm run build

CMD ["npm", "run", "start-fancy-web-pages-app"]