FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/backend-chess-app ./apps/backend-chess-app
COPY packages ./packages

RUN npm install

RUN npm run build

CMD ["npm", "run", "start-backend-chess-app"]