FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/frontend-chat-application ./apps/frontend-chat-application
COPY packages ./packages

EXPOSE 3008

RUN npm install

RUN npm run build

CMD ["npm", "run", "start-frontend-chat-app"]