name = "backend-medium-app"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTJjOWYzYzQtMjM0OC00ZjU4LWJiM2EtMTQ1MjcxOWYzZDRjIiwidGVuYW50X2lkIjoiYTFhZTYxNTAzZjJkYjRiZmU0NjJhMTBmYjUyNTJhOTM4OTcwNTBiNzBjOGUzYWNhMTU3OTgyOWQyMTBiODYyNCIsImludGVybmFsX3NlY3JldCI6IjBkNjlmODEzLTg3MmYtNDM3YS05ZDY2LWMxYTg3MTc3Y2E2YyJ9.pSfGGCmcXG4aUmS92UPHjKw40jI0MMi7zkbsAACR04U"
JWT_SECRET="secret"