import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/styles/shadcn-gray";
import { ThemeProvider } from "../utils/theme-provider"
import { SessionProviders } from "../utils/session-provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>
          <ThemeProvider attribute="class"  defaultTheme="dark" enableSystem disableTransitionOnChange>
            <Toaster position="bottom-center"/>
            {children}
          </ThemeProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
