name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.paytmApp
        push: true
        tags: anoopkarnik/turborepo-boilerplate-paytm-user-app:latest

    - name: Verify Pushed Image
      run: docker pull anoopkarnik/turborepo-boilerplate-paytm-user-app:latest  # Replace with your Docker Hub username and repository
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        DB_URL: ${{ secrets.DB_URL }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker stop paytm-user-app || true
          sudo docker rm paytm-user-app || true
          sudo docker rmi anoopkarnik/turborepo-boilerplate-paytm-user-app:latest || true
          sudo docker pull anoopkarnik/turborepo-boilerplate-paytm-user-app:latest
          sudo docker run --env-file ./env-files/.env --restart always -d --name paytm-user-app -p 3001:3001 anoopkarnik/turborepo-boilerplate-paytm-user-app:latest